name: Continuous Delivery (CD) pipeline

on:
  create:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Restore .NET tools
      run: dotnet tool restore

    - name: Execute Continuous Delivery (CD) pipeline
      run: dotnet dotnet-cake --target=CD --apiKey=${{ secrets.GITHUB_TOKEN }}
