name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:      
    - name: Cake Action
      uses: cake-build/cake-action@v1.1.1

